version: '3.8'

services:
  db_configuration:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ONETIME_PASSWORD=yes
    volumes:
#      - ./databases/configuration_data/mysql:/var/lib/mysql # -- disabled because of debug
      - ./databases/configuration_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - '3307:3306'
    restart: unless-stopped
    deploy:
      mode: global

  db_sensor:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_ONETIME_PASSWORD=yest
    volumes:
#      - ./databases/sensor_data/mysql:/var/lib/mysql # -- disabled because of debug
      - ./databases/sensor_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - '3308:3306'
    restart: unless-stopped
    deploy:
      mode: global