version: '3.8'
services:
  db_configuration:
    image: mysql:8.0.0
    environment:
      - MYSQL_USER=BitSneak
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
    volumes:
      - ./databases/configuration_data/mysql:/var/lib/mysql
      - ./databases/configuration_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - '3307:3306'
    deploy:
      mode: global
    secrets:
      - mysql_root_password
      - mysql_user_password

  db_sensor:
    image: mysql:8.0.0
    depends_on:
      - db_configuration
    environment:
      - MYSQL_USER=BitSneak
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
    volumes:
      - ./databases/sensor_data/mysql:/var/lib/mysql
      - ./databases/sensor_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - '3308:3306'
    deploy:
      mode: global
    secrets:
      - mysql_root_password
      - mysql_user_password

secrets:
  mysql_root_password:
    external: true
  mysql_user_password:
    external: true