version: "3.8"

services:
  db_configuration:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ONETIME_PASSWORD: "yes"
    volumes:
      - ./databases/configuration_data/mysql:/var/lib/mysql
      - ./databases/configuration_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    deploy:
      mode: global

  db_sensor:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ONETIME_PASSWORD: "yes"
    volumes:
      - ./databases/sensor_data/mysql:/var/lib/mysql
      - ./databases/sensor_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"
    deploy:
      mode: global

  db_user:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ONETIME_PASSWORD: "yes"
    volumes:
      - ./databases/user/mysql:/var/lib/mysql
      - ./databases/user/scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3309:3306"
    deploy:
      mode: global

  node_auth:
    image: node:22-alpine3.18
    environment:
      SERVER_PORT: 80
      DB_PASSWORD_USER: /run/secrets/db_pwd_user
      ACCESS_TOKEN_SECRET: /run/secrets/node_auth_access_token
      REFRESH_TOKEN_SECRET: /run/secrets/node_auth_refresh_token
    secrets:
      - db_pwd_user
      - node_auth_access_token
      - node_auth_refresh_token
    depends_on:
      - db_user
    working_dir: /app
    command: "node app.js"
    volumes:
      - ./node/authentication/:/app
    ports:
      - "81:80"
    deploy:
      mode: global

  node_rest:
    image: node:22-alpine3.18
    environment:
      SERVER_PORT: 80
      DB_PASSWORD_CONFIGURATION: /run/secrets/db_pwd_configuration
      DB_PASSWORD_SENSOR: /run/secrets/db_pwd_sensor
    secrets:
      - db_pwd_configuration
      - db_pwd_sensor
    depends_on:
      - db_configuration
      - db_sensor
      - node_auth
    working_dir: /app
    command: "node app.js"
    volumes:
      - ./node/rest/:/app
    ports:
      - "80:80"
    deploy:
      mode: global

secrets:
  db_pwd_configuration:
    external: true
  db_pwd_sensor:
    external: true
  db_pwd_user:
    external: true
  node_auth_access_token:
    external: true
  node_auth_refresh_token:
    external: true