version: '3.8'
services:
  db_configurations:
    image: mysql:8.0.0
    environment:
      - MYSQL_USER=BitSneak
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
    volumes:
      - ./databases/configuration_data/data:/var/lib/mysql
      - ./databases/configuration_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - '3307:3306'
    secrets:
      - mysql_root_password
      - mysql_user_password

  db_sensors:
    image: mysql:8.0.0
    environment:
      - MYSQL_USER=BitSneak
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_user_password
    volumes:
      - ./databases/sensor_data/data:/var/lib/mysql
      - ./databases/sensor_data/scripts:/docker-entrypoint-initdb.d/
    ports:
      - '3308:3306'
    secrets:
      - mysql_root_password
      - mysql_user_password

secrets:
  mysql_root_password:
    external: true
  mysql_user_password:
    external: true