GRANT ALL PRIVILEGES ON *.* TO 'admin' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON ship.* TO 'developer';
GRANT ALL PRIVILEGES ON certificate.* TO 'developer';
GRANT ALL PRIVILEGES ON corporation.* TO 'developer';

GRANT SELECT, INSERT, UPDATE ON ship.* TO 'api';
GRANT SELECT, INSERT, UPDATE ON certificate.* TO 'api';
GRANT SELECT, INSERT, UPDATE ON corporation.* TO 'api';

FLUSH PRIVILEGES;