INSERT INTO threshold.parameter (name, unit)
VALUES ('Air Pressure', 'Pa'),
       ('Humidity', '%'),
       ('Temperature', '°C'),
       ('Vibration', 'm/s²'),
       ('Altitude', 'm'),
       ('Latitude', 'DD'),
       ('Longitude', 'DD');

INSERT INTO threshold.rule (name)
VALUES ('>'),
       ('<'),
       ('=='),
       ('!='),
       ('>='),
       ('<=');

INSERT INTO threshold.level (name, priority)
VALUES ('Critical', 1),
       ('High', 2),
       ('Medium', 3),
       ('Low', 4),
       ('Ok', 5);

INSERT INTO threshold.threshold (container_id, parameter, rule, level, value)
VALUES (1, (SELECT id FROM threshold.parameter WHERE name = 'Air Pressure'),
        (SELECT id FROM threshold.rule WHERE name = '>'), (SELECT id FROM threshold.level WHERE name = 'Critical'),
        101.325),
       (1, (SELECT id FROM threshold.parameter WHERE name = 'Humidity'),
        (SELECT id FROM threshold.rule WHERE name = '<'), (SELECT id FROM threshold.level WHERE name = 'High'),
        50.00000),
       (1, (SELECT id FROM threshold.parameter WHERE name = 'Temperature'),
        (SELECT id FROM threshold.rule WHERE name = '=='), (SELECT id FROM threshold.level WHERE name = 'Medium'),
        25.00000),
       (1, (SELECT id FROM threshold.parameter WHERE name = 'Vibration'),
        (SELECT id FROM threshold.rule WHERE name = '!='), (SELECT id FROM threshold.level WHERE name = 'Low'),
        9.80000),
       (1, (SELECT id FROM threshold.parameter WHERE name = 'Altitude'),
        (SELECT id FROM threshold.rule WHERE name = '>='), (SELECT id FROM threshold.level WHERE name = 'Ok'),
        100.00000),
       (1, (SELECT id FROM threshold.parameter WHERE name = 'Latitude'),
        (SELECT id FROM threshold.rule WHERE name = '>'), (SELECT id FROM threshold.level WHERE name = 'Critical'),
        45.00000),
       (1, (SELECT id FROM threshold.parameter WHERE name = 'Longitude'),
        (SELECT id FROM threshold.rule WHERE name = '<'), (SELECT id FROM threshold.level WHERE name = 'High'),
        90.00000),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Air Pressure'),
        (SELECT id FROM threshold.rule WHERE name = '>'), (SELECT id FROM threshold.level WHERE name = 'Medium'),
        101.325),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Humidity'),
        (SELECT id FROM threshold.rule WHERE name = '<'), (SELECT id FROM threshold.level WHERE name = 'Low'),
        50.00000),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Temperature'),
        (SELECT id FROM threshold.rule WHERE name = '=='), (SELECT id FROM threshold.level WHERE name = 'Ok'),
        25.00000),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Vibration'),
        (SELECT id FROM threshold.rule WHERE name = '!='), (SELECT id FROM threshold.level WHERE name = 'Low'),
        9.80000),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Altitude'),
        (SELECT id FROM threshold.rule WHERE name = '>='), (SELECT id FROM threshold.level WHERE name = 'Ok'),
        100.00000),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Latitude'),
        (SELECT id FROM threshold.rule WHERE name = '>'), (SELECT id FROM threshold.level WHERE name = 'Critical'),
        45.00000),
       (2, (SELECT id FROM threshold.parameter WHERE name = 'Longitude'),
        (SELECT id FROM threshold.rule WHERE name = '<'), (SELECT id FROM threshold.level WHERE name = 'High'),
        90.00000);