name: Build and Send Thesis

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache LaTeX packages
        uses: actions/cache@v2
        with:
          path: /usr/local/texlive
          key: ${{ runner.os }}-texlive-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-texlive-

      - name: Update package lists
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential make-guile pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at

      - name: Install TexLive
        run: |
          sudo apt-get install -y texlive-full

      - name: Build thesis
        run: |
          # Move to Diplomarbeit directory
          cd Diplomarbeit

          # Compile the thesis
          pandoc \
            -s \
            -o diplomarbeit.pdf \
            10-einleitung.md \
            20-zielsetzung.md \
            30-ausarbeitungen.md \
            31-ausarbeitung_schrempf.md \
            32-ausarbeitung_gekle.md \
            33-ausarbeitung_kampl.md \
            40-zusammenfassung.md \
            90-Projektplan.md \
            95-Projektdokumentation.md \
            99-Projektabschlussbericht.md \
            --bibliography=literatur.bib \
            --filter pandoc-citeproc \
            --metadata-file=metadata.yaml \
            --pdf-engine=pdflatex

      - name: Move PDF to root directory
        run: mv Diplomarbeit/diplomarbeit.pdf diplomarbeit.pdf

      - name: List files after build
        run: |
          ls
          ls Diplomarbeit

      - name: Zip repository
        run: zip -r repository.zip .

      - name: Send Zip via Email
        uses: dawidd6/action-send-mail@v2
        with:
          subject: "Repository Archive"
          body: "Attached is the repository archive."
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: 201wita27@o365.htl-leoben.at
          attachments: "repository.zip"
