name: Zip and Send Repository

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download and cache dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at

      - name: Change directory to LaTeX folder
        run: cd Diplomarbeit

      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error Diplomarbeit/main.tex

      - name: Move PDF to root directory
        run: mv Diplomarbeit/main.pdf .

      - name: Zip repository
        run: zip -r repository.zip .

      - name: Send Zip via Email
        uses: dawidd6/action-send-mail@v2
        with:
          subject: "Repository Archive"
          body: "Attached is the repository archive."
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: 201wita27@o365.htl-leoben.at
          attachments: "repository.zip"
