name: Zip and Send Repository

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update package lists
        run: sudo apt-get update

      - name: Download and cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.texlive
          key: texlive-full-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            texlive-full-${{ runner.os }}-
            texlive-full-

      - name: Install texlive-full
        if: steps.cache.outputs.cache-hit != 'true'
        run: sudo apt-get install -y texlive-full pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at

      - name: List files in Diplomarbeit directory
        run: |
          ls Diplomarbeit

      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error Diplomarbeit/main.tex || true

      - name: Move PDF to root directory
        run: mv Diplomarbeit/main.pdf .

      - name: List files in root directory
        run: ls

      - name: Zip repository
        run: zip -r repository.zip .

      - name: Send Zip via Email
        uses: dawidd6/action-send-mail@v2
        with:
          subject: "Repository Archive"
          body: "Attached is the repository archive."
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: 201wita27@o365.htl-leoben.at
          attachments: "repository.zip"
