
name: Build and Send Thesis

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip repository
        run: | 
           zip -r repository.zip .
         
      - name: Zip and Send File via Email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.office365.com
          port: 587
          account: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          sender: GitHub
          from: ${{ secrets.OUTLOOK_EMAIL }}
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          subject: "Repository Archive"
          body: " "
          attachments: repository.zip
