name: Build and Send Thesis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential make-guile texlive-full pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at

          
      - name: Build DA-Thesis
        run: |
          make pdf -C HTLLE-DA-Vorlage SOURCEDIR=../Diplomarbeit/

      - name: Zip repository
        run: |
          zip -r repository.zip .

      - name: List files for debugging
        run: ls -lh repository.zip

      - name: Zip and Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.protonmail.com
          server_port: 465 
          username: diplomarbeitcontrude@proton.me
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Repository Archive"
          body: " "
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: diplomarbeitcontrude@proton.me
          attachments: repository.zip
