name: Build and Send Thesis

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Cache apt lib
        uses: actions/cache@v3
        with:
          path: /var/lib/apt
          key: ${{ runner.os }}-apt-lib
          restore-keys: |
            ${{ runner.os }}-apt-lib
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential make-guile texlive-full pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at
        
      - name: Build DA-Thesis
        run: |
          make pdf -C HTLLE-DA-Vorlage SOURCEDIR=../Diplomarbeit/

      - name: Zip repository
        run: |
          zip -r repository.zip .

      - name: List files for debugging
        run: ls -lh repository.zip

      - name: Zip and Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: diplomarbeitcontrude@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Repository Archive"
          body: " "
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: diplomarbeitcontrude@gmail.com
          attachments: repository.zip
