name: Build and Send Thesis

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip repository
        run: |
          zip -r repository.zip .

      - name: List files for debugging
        run: ls -lh repository.zip

      - name: Zip and Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: diplomarbeitcontrude@gmail.com
          password: markoISTKLEINsoca149
          subject: "Repository Archive"
          body: " "
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: ${{ secrets.OUTLOOK_EMAIL }}
          attachments: repository.zip
