name: Build and Send Thesis

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip repository
        run: |
          zip -r repository.zip .

      - name: List files for debugging
        run: ls -lh repository.zip

      - name: Send File via Email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.gmail.com
          port: 587
          account: diplomarbeitcontrude@gmail.com
          password: markoISTKLEINsoca149
          sender: diplomarbeitcontrude@gmail.com
          from: diplomarbeitcontrude@gmail.com
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          subject: "Repository Archive"
          body: "Archived Repo"
          attachments: '[{"path": "repository.zip"}]'
