name: Build and Send Thesis

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip repository
        run: | 
           zip -r Diplomarbeit/build/repository.zip .

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit zip file
        run: |
          git add Diplomarbeit/build/repository.zip
          git commit -m "Add repository.zip to build directory"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
         
      - name: Zip and Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: "Repository Archive"
          body: " "
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: ${{ secrets.OUTLOOK_EMAIL }}
          attachments: Diplomarbeit/build/repository.zip
