name: Build and Send Thesis

on:
  push:
    branches:
      - main
    paths:
      - Diplomarbeit/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore packages
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ runner.os }}-da-packages

      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential make-guile texlive-full pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at

      - name: Save packages
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ steps.cache-restore.outputs.cache-da-packages }}
        
      - name: Build DA-Thesis
        run: |
          make pdf -C HTLLE-DA-Vorlage SOURCEDIR=../Diplomarbeit/

      - name:  Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_MAIL }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Diploma thesis"
          body: " "
          to: ${{ secrets.TEAMS_MAIL }}
          from: ${{ secrets.GMAIL_MAIL }}
          attachments: Diplomarbeit/diplomarbeit.pdf
