name: Build and Zip Thesis
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Zip repository
        run: | 
           zip -r Diplomarbeit/build/repository.zip .
      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Commit zip file
        run: |
          git add Diplomarbeit/build/repository.zip
          git commit -m "Add repository.zip to build directory"
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
         
