name: Zip and Send Repository

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update APT and install LaTeX and Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive \
            texlive-latex-extra \
            texlive-fonts-recommended \
            pandoc \
            pandoc-citeproc \
            tree \
            rsync \
            hunspell \
            hunspell-de-at

      - name: List files in Diplomarbeit directory
        run: |
          ls Diplomarbeit

      - name: Compile LaTeX document
        run: |
          ls Diplomarbeit
          pdflatex -interaction=nonstopmode -halt-on-error Diplomarbeit/Diplomarbeit.tex || true
          pdflatex -interaction=nonstopmode -halt-on-error Diplomarbeit/Diplomarbeit.tex || true

      - name: Move PDF to root directory
        run: mv Diplomarbeit/Diplomarbeit.pdf .

      - name: List files in root directory
        run: ls

      - name: Zip repository
        run: zip -r repository.zip .

      - name: Send Zip via Email
        uses: dawidd6/action-send-mail@v2
        with:
          subject: "Repository Archive"
          body: "Attached is the repository archive."
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: 201wita27@o365.htl-leoben.at
          attachments: "repository.zip"
