name: Send Thesis to Teams

on: 
  workflow_run:
    workflows: ["Build and Zip Thesis"]
    types:
      - completed

jobs:
  dependent_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip and Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: "Repository Archive"
          body: " "
          to: 2c5ec9b6.O365.htl-leoben.at@emea.teams.ms
          from: ${{ secrets.OUTLOOK_EMAIL }}
          attachments: Diplomarbeit/build/repository.zip
