name: Deploy to Server

on:
  push:
    branches:
      - server_dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and redeploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Contrude
            git pull
            sudo docker stack rm contrude
            sudo docker stack deploy -c ~/Contrude/Container/compose.yml contrude
